# This is a basic workflow to help you get started with Actions

name: CI_Sample

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add mac other actions to build,
          echo test, and deploy your project.
          
  Android:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: XamarinMaterialSample_Android
      run: |
        echo STEP_1
        ls
        pwd
        echo STEP_2
        echo -->cd XamarinMaterialSample
        echo STEP_3
        ls
        pwd
        echo STEP_4
        nuget restore
        echo STEP_4_2
        echo -->cd ..
        echo STEP_4_3
        ls
        pwd
        echo STEP_5
        cd XamarinMaterialSample.Android
        echo STEP_6
        ls
        pwd
        echo STEP_7
        msbuild XamarinMaterialSample.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  AndroidArt:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: XamarinMaterialSample_Android_APK
      run: |
        steps:
          - uses: actions/checkout@master
          - name: Building APK
            uses: ./action
            with:
              args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk ${{env.SOLUTION_NAME}}/${{env.ANDROID_PROJECT_NAME}}/${{env.ANDROID_PROJECT_NAME}}.csproj
          - name: Artifacts
            run: |
              mkdir -p apks
              cp ${{env.SOLUTION_NAME}}/${{env.ANDROID_PROJECT_NAME}}/bin/Debug/*.apk apks
          - name: Upload Artifacts
            uses: actions/upload-artifact@v1
            with:
              name: apks
              path: apks
        
  iOS:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: XamarinMaterialSample_iOS
      run: |
        echo -->cd XamarinMaterialSample
        nuget restore
        msbuild XamarinMaterialSample.iOS/XamarinMaterialSample.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
